read_task:
  description: >
    作为文档阅读专家，你需要仔细阅读整个招标文档内容。重点关注以下方面：
    1. 项目基本信息：包括项目名称、编号、金额、规模等基础信息
    2. 时间节点信息：包括挂网时间、报名时间、开标时间、截止时间等关键时间点
    3. 项目具体要求：包括技术要求、资质要求、服务范围等
    4. 招标方信息：包括招标单位背景、联系方式等
    
    请确保不遗漏任何重要信息，为后续分析工作打好基础。
  expected_output: "一份完整的文档关键信息概述，包含所有重要细节且内容无误"

analyze_task:
  description: >
    基于前序阅读任务的结果，请系统分析并提取以下具体信息，必须严格按照以下JSON格式返回：
    {
      "publish_time": "挂网时间，格式：YYYY-MM-DD",
      "project_name": "完整的项目名称",
      "project_period": "项目周期,即项目预计持续时间,单位年",
      "project_target": "项目的具体内容和目标",
      "project_amount": "项目标的，也就是项目金额，单位万元",
      "business_scenario": "项目应用的具体场景，其中包括[国际快递][日常快递][票据传递]几种类型",
      "tender_unit": "招标单位,招标方的完整名称",
      "register_deadline": "投标报名的最后期限，格式：YYYY-MM-DD",
      "submit_deadline": "标书提交的截止时间，格式：YYYY-MM-DD",
      "open_time": "开标的具体时间，格式：YYYY-MM-DD"
    }
    
    注意：
    1. 必须返回完整的JSON格式数据
    2. 所有字段都必须填写，如果找不到相关信息，填写"未提供"
    3. 时间字段必须使用YYYY-MM-DD格式
    4. 不要添加任何额外的字段
    5. 不要在JSON之外添加任何其他内容
  expected_output: "按照指定格式的JSON数据" 